Portfolio-mobile1
Hazard10-eng/Portfolio pull request #14
Opened 2023-02-16 09:11 UTC by Hazard10-eng

Add HTML file
Add CSS file
Check linters error

2023-02-16 10:24 UTC, Olamarx requested changes
Hi @gaks1,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- Linters passed ✔️ 
- Readme file ✔️ 
- correct tags ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 10:24 UTC, Olamarx commented on index.html
> +        />
- [ ] I would implore you to use the image from the css as a background image, because decorations are always backgrounded images, not img tags

2023-02-16 10:24 UTC, Olamarx commented on index.html
>              <img src="./image/Counter.svg" alt="counter" />
- [ ] I would advise you to use the image from background because decorations are always backgrounded images, not img tags

2023-02-16 16:52 UTC, algerina requested changes
Hi @abel-tefera  ,

Good job so far!  But still some minor issues to complete.

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- No linters errors:heavy_check_mark:



## STATUS: REQUIRED CHANGES 


<img src="https://media3.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/>

 ##required changes:

- Please check the comments under the review

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-02-16 16:52 UTC, algerina commented on index.html
>              <img src="./image/Counter.svg" alt="counter" />
- [ ] Kindly implement the change required by the previous reviewer.

2023-02-16 16:52 UTC, algerina commented on index.html
- [ ] Kindly fix the position of the social media icons, as well as the frameworks and skills section (color, position).
![review](https://user-images.githubusercontent.com/53347966/219433243-9f228e6c-387c-49dc-a00b-03cdeb762df3.JPG)

2023-02-17 12:21 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @Hazard10-eng   👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️professional PR👍 
✔️professional README👍 
✔️No Linter Errors👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 12:59 UTC, merged